services:
  nginx:
    env_file: [ .env ]
    build:
      dockerfile: build/nginx.Dockerfile
      args:
        API_HOST: $API_HOST
        API_PORT: $API_PORT
        NGINX_PORT: $NGINX_PORT
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"