"""Messages table

Revision ID: f4e6bf29704f
Revises: a5b0c90b8c55
Create Date: 2024-10-23 15:28:09.712191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e6bf29704f'
down_revision: Union[str, None] = 'a5b0c90b8c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['instant_chat.chat.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['instant_chat.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='instant_chat'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message', schema='instant_chat')
    # ### end Alembic commands ###
